server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5415/semantic_db
    username: postgres
    password: postgres

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3.1:8b

      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true
